import React from 'react';

function About() {

    return (
        <div className="container">
            
            <div className='card  border border-light' id='about1'>
                <img src='https://wallpaperaccess.com/full/2651908.png' className='card-img-top' alt='eldenrings'></img><br></br>
                <div className='card-body' id='about2'>
                    <h1 className='card-title text-center text-dark bg-warning rounded border border-light p-2 m-2'>Welcome to the world of the Lands Between!</h1><bg></bg><bg></bg>
                    
                    <h2 className='card-title text-center text-danger m-2'>  </h2><br></br><br></br>
                    <h4 className='text-warning p-2 font-weight-light m-2'>Elden Ring is a third-person action RPG with a dark fantasy setting where the story revolves around the Elden Ring. Legend has it that the ring holds unimaginable power "that which commanded the stars, giving life its fullest brilliance" and that the ring has been destroyed by something or someone. This then leads to the destruction and decay of the world, the sky burning, and brings parallels to the collapsing sun of the Souls universe.</h4><br></br>
                    <h4 className='text-warning p-2 font-weight-light m-2'>The Tarnished is one of many exiles called back to the Lands Between in hopes of repairing the Elden Ring and becoming the next Elden Lord. Early on in their journey, the Tarnished encounters a Maiden named Melina. As the Tarnished is Maidenless, Melina offers to act as their Maiden, granting them the ability to turn runes into strength, under the condition that the Tarnished bring her to the base of the Erdtree where she can fulfill her purpose. She also takes the Tarnished to the Roundtable Hold, a gathering place for other Tarnished seeking to repair the Elden Ring. There, the Tarnished learns from their divine benefactor, the Two Fingers, that in the wake of the Shattering and Queen Marika's disappearance, her demigod children had taken the Great Runes, pieces of the Elden Ring, for themselves. Corrupted by the influence of the shards, the demigods now war against each other to try and obtain the other Great Runes. The Tarnished is instructed to collect the Great Runes and bring them to the Erdtree, where they can be used to repair the Elden Ring.</h4><br></br>
                    <h4 className='text-warning p-2 font-weight-light m-2'>The Tarnished proceeds to journey into the Lands Between, investigating its various locales and defeating the demigods. Eventually, the Tarnished recovers enough Great Runes so that Two Fingers allows them to confront Morgott the Grace-Given, the demigod guarding the Erdtree. As he dies, Morgott claims that the Erdtree will not allow anyone to enter it, making the Elden Ring irreparable. The Tarnished confirms this when they approach the Erdtree and find their way blocked by a wall of thorns. Melina then arrives and advises that they journey to find the Flame of Ruin, which they can use to set the Erdtree on fire and burn away the thorns. Upon learning the Tarnished was rebuffed from the Erdtree, Two Fingers withdraws from the mortal plane to consider its next move, leaving the Tarnished free to proceed with Melina's plan, or search for the imprisoned Three Fingers to gain the power of the Frenzied Flame.</h4><br></br>
                    <h4 className='text-warning p-2 font-weight-light m-2'>Upon obtaining the Flame of Ruin, if the Tarnished did not free the Three Fingers, then Melina will take the flame and sacrifice herself to set the Erdtree on fire. If the Tarnished freed the Three Fingers, then Melina will abandon the Tarnished, forcing them to use the Frenzied Flame to set the Erdtree on fire. Regardless, the Tarnished is transported to the ruined city of Farum Azula while the Erdtree burns. After defeating Maliketh the Black Blade and harnessing his power to fuel the fire, they are returned to the foot of the Erdtree, which has now been burnt to ash. As the Tarnished ascends towards the Erdtree, they battle fellow Roundtable Hold member Gideon Ofnir, as well as the First Elden Lord Godfrey to gain access to the interior. Inside, they fight the reanimated remains of Queen Marika's consort and alter ego, Radagon. Once Radagon is defeated, the Elden Beast, the true form of the Elden Ring, reveals itself. After the beast is vanquished, the Tarnished finally gains access to Queen Marika's shattered corpse, which contains the remains of the Elden Ring. Depending on the Tarnished's actions throughout the game, six different endings can then be achieved, ranging from the Tarnished becoming the Elden Lord in some form, allowing Marika to be usurped by Ranni the Witch, or using the Frenzied Flame to destroy the Lands Between.</h4><br></br>
                   
                </div>
            </div><br></br><br></br>
            <h6 className='text-light text-left'>&copy; Derin DeNio 2022</h6>
        </div>
    )

    }
export default About;